# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: HEEJIN LEE #Bay Jekyll Theme #상태표시줄?탭 이름 
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.

# baseurl: "/bay" # the subpath of the site  #default였음
baseurl: ""
# url: "https://eliottvincent.github.io" # the base hostname & protocol for the site #default였음
# url: "https://hjiiinlee.github.io/" # 
url: ""
og_image: /assets/img/profilepic.jpg  #안되면 여기 있는 파일명과 동일한 파일명 (profile-pic)을 사용해서 내 사진을 올려보자. 아예 다른 파일을 올리는 방법은 추후 고민 
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Academic Backgrounds #Work
    - name: Publications 
    - name: Projects #Blog
    - name: Work Experience #Blog


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: hjiiin3@snu.ac.kr
      link: mailto:hjiiin3@snu.ac.kr
      
   # - name: WeChat
   #   value: YourWeChatUsername
   #   link: "#"
   # 한 번에 # 붙이려면 ctrl + / 
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    # - name: LinkedIn
    #   link: https://www.linkedin.com/in/heejin-lee-b10bb9106   
    
    - name: ORCiD
      link: https://orcid.org/0000-0002-6811-6726   

    # - name: GitHub
    #   link: http://github.com/YourGitHubUsername
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: RSS
    #   link: /feed.xml
# ORCID는 기본으로 들어가 있지 않아서 나중에 어떤 식으로 짜서 넣을지 고민해보기 ! 

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
